### ISSUE TITLE
[20240525] 게시판 수정, 로그인 API 불러오기 코드 구현 

### ISSUE THREAD

**Issue by aranlll** [Chaeyeon0/GreenDay_Study#27]
### 전까지 했던 내용 .. (쓰는걸 까먹엇습니댯...제송함니댯..🥲)

-   게시판 내용 수정 

1.  게시판 레이아웃 완성 
2.  입력 칸 코드 작성
3. 등록 버튼, 입력 후 등록 누르면 보이게 하는 코드 작성

![image](https://github.com/Chaeyeon0/GreenDay_Study/assets/163715414/92bee8d0-9aee-4fba-8a03-1f1da99fc89f)

![image](https://github.com/Chaeyeon0/GreenDay_Study/assets/163715414/d5097ff2-bdc3-48bd-a2be-655286e8b0cb)

```html
      <input
        className="input"
        style={{ whiteSpace: "pre-wrap" }}
        onChange={onChange}
        value={text}
      ></input>
      <div>
        <button className="backrock_button" style={{ whiteSpace: "pre-wrap" }}>
          <img
            src="backrock_button.png"
            onClick={() => {
              setOldText({ text });
              setOldText(text);
            }}
          />
        </button>
      </div>
``` 
```css
@import url('https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap');

.input{
  position:absolute;
  left: 275px;
  top:40px;
  width: 1025px;
  padding: 60px;
  padding-bottom: 100px;
  border : 2px solid grey;
  border-radius: 15px;
  font-size: 30px;
  font-family: "Nanum Pen Script", cursive;

}

.input1{
  border-bottom: 2px solid grey;
  padding-bottom: 15px;
  padding-top: 15px;
  font-weight: bold;
  padding-left: 15px;
}
.input2{
  font-size: 25px;
  font-family: "Nanum Pen Script", cursive;
  padding-top: 20px;
}

.input_data_list{
  position:absolute;
  left:275px;
  border-bottom : 2px solid grey;
  border-top : 2px solid grey;
  top: 300px;
  width: 1150px;
  text-align: left;
  padding-bottom: 60px;
}

.backrock_button{
  border: none;
}

.backrock_button img{
  position: absolute;
  left:1300px;
  width:90px;
  top:180px;
  border:none;
}
``` 
### 게시판 수정

혜원언니랑 상의 후에 글을 쓰는 부분이랑 글이 보여지는 부분이랑 따로 있는게 더 좋을 거 같다는 결정에 따라 바아로 게시판 수정 !!! 

서버에서 데이터 불러오기 위한 axios 를 다시 설치하려고 했는데요 ..? 

<img src="https://github.com/Chaeyeon0/GreenDay_Study/assets/163715414/53b72aac-9e77-484a-b292-e86fb761e921" width="70%">

왜 안되는 건가요 ... ? 
찾아봣더니 스크립트 실행 권한을 새로 설정해줘야한다길래 

```shell
get-ExecutionPolicy
Set-ExecutionPolicy RemoteSigned
```  
이거 두개 powershell에 입력하고 다시 하니 설치 완료 햇습니다 !!
